#服务器端口
server:
  port: 8086
#数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.199.202.220:3306/meishizaixian
    username: user7
    password: User123456
    #模板
  thymeleaf:
    #\开启缓存:true 开发阶段建议关闭
    cache: false
    servlet:
     content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
#redis支持的五种数据类型:string(字符串) hash(哈希) list(列表) set(集合) zset(有序集合)
#springboot整合redis第二步
redis:
  #redis服务器的ip地址
  host: 192.168.43.36
  #redis服务器的端口号
  port: 6379



#别名定义
mybatis:
    type-aliases-package: com.gaoshu.model
  #加载全局配置文件
    config-location: classpath:SqlMapConfig.xml
    #加载映射配置文件
    mapper-locations: classpath:mapper/*Mapper.xml